    <?php

    namespace Database\Seeders;

    use App\Models\FeFramework;
    use Illuminate\Database\Console\Seeds\WithoutModelEvents;
    use Illuminate\Database\Seeder;

    class FrontendStackSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         */
        public function run(): void
        {

            $frameworks = [
                "Angular.js",
                "React.js",
                "Vue.js",
                "Ember.js",
                "Backbone.js",
                "Meteor.js",
                "D3.js",
                "Three.js",
                "Chart.js",
                "Socket.io",
                "Polymer.js",
                "Aurelia.js",
                "Knockout.js",
                "Mithril.js",
                "Riot.js",
                "Cycle.js",
                "Redux.js",
                "MobX",
                "RxJS",
                "Dojo Toolkit",
                "Feathers.js",
                "Keystone.js",
                "Sails.js",
                "NestJS",
                "LoopBack",
                "Hapi.js",
                "Nuxt.js",
                "Next.js",
                "Gatsby.js",
                "Quasar Framework",
                "Electron.js",
                "Cordova",
                "PhoneGap",
                "NativeScript",
                "Ionic",
                "React Native",
                "Onsen UI",
                "Sencha Ext JS",
                "jQuery",
                "Prototype.js",
                "Underscore.js",
                "Lodash",
                "Moment.js",
                "CamanJS",
                "Fabric.js",
                "Paper.js",
                "Phaser",
                "Babylon.js",
                "A-Frame",
                "Popmotion",
                "GreenSock Animation Platform (GSAP)",
                "TensorFlow.js",
                "Brain.js",
                "Synaptic",
                "Synaptic.js",
                "ConvNetJS",
                "Cytoscape.js",
                "P5.js",
                "CreateJS",
                "Bee.js",
                "Crafty.js",
                "Enchant.js",
                "PlayCanvas",
                "ZingChart",
                "Chaplin.js",
                "CanJS",
                "Flight.js",
                "Hammer.js",
                "Knockback.js",
                "Leaflet",
                "Mapbox GL JS",
                "React Leaflet",
                "Cesium",
                "Bonsai",
                "Reveal.js",
                "impress.js",
                "Deck.js",
                "Hovercraft",
                "Remark",
                "Strut",
                "Reveal.js",
                "impress.js",
                "Deck.js",
                "Hovercraft",
                "Remark",
                "Strut",
                "PhantomJS",
                "Mocha",
                "Jasmine",
                "Jest",
                "Cypress",
                "QUnit",
                "Nightwatch.js",
                "Protractor",
                "Karma",
                "JSDOM",
                "Enzyme",
                "Ava",
                "Webix",
                "React Bootstrap",
                "Material-UI",
                "Ant Design",
                "Vuetify",
                "Element UI",
                "Quasar Framework",
                "Bootstrap",
                "Foundation",
                "Semantic UI",
                "Bulma",
                "UIKit",
                "Pure.css",
                "Skeleton",
                "Milligram",
                "Siimple",
                "Water.css"
            ];
            
            foreach ($frameworks as $index => $framework) {
                FeFramework::create([
                    'id' => $index + 1,
                    'name' => $framework,
                ]);
            }
        }
    }
