version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatcompstack-backend
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/whatcompstack-BE
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=whatcompstack
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: whatcompstack-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: whatcompstack
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
