<?php
 $backend = [
  
    "Python" => "python", 
    "Django" => "django", 
    "Flask" => "flask", 
    "Pyramid" => "pyramid", 
    "Bottle" => "bottle", 
    "CherryPy" => "cherrypy", 
    "TurboGears" => "turbogears", 
    "Web2Py" => "web2py", 
    "Tornado" => "tornado",
    "Falcon" => 'falcon',

   
    "JavaScript" => "javascript", 
    "Node.js" => "node.js", 
    "Express.js" => "express.js", 
    "Nest.js" => "nest.js", 
    "Hapi.js" => "hapi.js", 
    "Koa.js" => "koa.js", 
    "Sails.js" => "sails.js", 
    "Meteor.js" => "meteor.js", 
    "Adonis.js" => "adonis.js",

    "Java" => "java", 
    "Spring Boot" => "spring boot", 
    "Apache Struts" => "apache struts", 
    "Play Framework" => "play framework", 
    "Grails" => "grails", 
    "Dropwizard" => "dropwizard", 
    "JavaServer Faces (JSF)" => "javaserver faces (jsf)",
    "Vert.x" => "vert.x", 
    "Apache Wicket" => "apache wicket", 
    "Apache Tapestry" => "apache tapestry", 
    "Spark" => "spark", 
    "JHipster" => "jhipster",

    "Ruby" => "ruby", 
    "Ruby on Rails" => "ruby on rails", 
    "Sinatra" => "sinatra", 
    "Hanami" => "hanami", 
    "Cuba" => "cuba", 
    "Ramaze" => "ramaze", 
    "Volt" => "volt", 
    "Roda" => "roda", 
    "Trailblazer" => "trailblazer",

    
    "PHP" => "php", 
    "Laravel" => "laravel", 
    "Symfony" => "symfony", 
    "CodeIgniter" => "codeigniter", 
    "Yii" => "yii", 
    "Zend Framework" => "zend framework", 
    "Phalcon" => "phalcon", 
    "CakePHP" => "cakephp", 
    "FuelPHP" => "fuelphp",
    "Slim" => "slim", 
    "Lumen" => "lumen",

 
    "Go" => "go", 
    "Gin" => "gin", 
    "Echo" => "echo", 
    "Revel" => "revel", 
    "Buffalo" => "buffalo", 
    "Fiber" => "fiber", 
    "Martini" => "martini", 
    "Beego" => "beego", 
    "Goji" => "goji", 
    "Kemal" => "kemal", 
    "Gorilla" => "gorilla",

   
    "C#" => "c#", 
    "ASP.NET" => "asp.net", 
    ".NET Core" => ".net core", 
    "Nancy" => "nancy", 
    "ServiceStack" => "servicestack", 
    "Akka.NET" => "akka.net", 
    "Simple.Web" => "simple.web", 
    "Orchard Core" => "orchard core",
    "MVC Framework" => "mvc framework", 
    "Web API" => "web api",

    "Rust" => "rust", 
    "Rocket" => "rocket", 
    "Actix" => "actix", 
    "Warp" => "warp", 
    "Tide" => "tide", 
    "Nickel" => "nickel", 
    "Iron" => "iron", 
    "Gotham" => "gotham", 
    "Rocket Framework" => "rocket framework", 
    "Thruster" => "thruster",

   
    "Elixir" => "elixir", 
    "Phoenix" => "phoenix", 
    "Nerves" => "nerves", 
    "Sugar" => "sugar", 
    "Rocket" => "rocket", 
    "Maru" => "maru", 
    "Cavalry" => "cavalry", 
    "Raxx" => "raxx",

   
    "Kotlin" => "kotlin", 
    "Ktor" => "ktor", 
    "Spring Boot" => "spring boot", 
    "Micronaut" => "micronaut", 
    "Vert.x" => "vert.x", 
    "Jooby" => "jooby", 
    "Javalin" => "javalin", 
    "TorqueBox" => "torquebox",

    "Swift" => "swift", 
    "Vapor" => "vapor", 
    "Perfect" => "perfect", 
    "Kitura" => "kitura", 
    "Zewo" => "zewo", 
    "GCDWebServer" => "gcdwebserver", 
    "Blackfish" => "blackfish", 
    "Swifter" => "swifter", 
    "Noze.io" => "noze.io",

  
    "Scala" => "scala", 
    "Play Framework" => "play framework", 
    "Lift" => "lift", 
    "Finatra" => "finatra", 
    "Scalatra" => "scalatra", 
    "Akka" => "akka", 
    "Skinny" => "skinny", 
    "Sangria" => "sangria",

    
    "Dart" => "dart", 
    "Aqueduct" => "aqueduct", 
    "Angel" => "angel", 
    "Shelf" => "shelf", 
    "Jaguar" => "jaguar", 
    "Redstone" => "redstone", 
    "Dio" => "dio", 
    "Grinder" => "grinder",

   
    "Lua" => "lua", 
    "Lapis" => "lapis", 
    "OpenResty" => "openresty", 
    "Mercury" => "mercury", 
    "WSAPI" => "wsapi", 
    "Turbo.lua" => "turbo.lua", 
    "Orbit" => "orbit", 
    "CGILua" => "cgilua", 
    "Nginx" => "nginx",

 
    "Clojure" => "clojure", 
    "Luminus" => "luminus", 
    "Ring" => "ring", 
    "Duct" => "duct", 
    "Compojure" => "compojure", 
    "Pedestal" => "pedestal", 
    "Buddy" => "buddy", 
    "Immutant" => "immutant",

   
    "R" => "r", 
    "Shiny" => "shiny", 
    "Plumber" => "plumber", 
    "httpuv" => "httpuv", 
    "opencpu" => "opencpu", 
    "RestRserve" => "restrserve", 
    "FastRWeb" => "fastrweb", 
    "rApache" => "rapache", 
    "Rook" => "rook",

    "Julia" => "julia", 
    "Genie" => "genie", 
    "HTTP.jl" => "http.jl", 
    "Mux.jl" => "mux.jl", 
    "Franklin.jl" => "franklin.jl", 
    "Julienned" => "julienned", 
    "Escher" => "escher", 
    "WebIO" => "webio", 
    "Architect" => "architect",

   
    "Perl" => "perl", 
    "Mojolicious" => "mojolicious", 
    "Dancer" => "dancer", 
    "Catalyst" => "catalyst", 
    "Plack" => "plack", 
    "WebPerl" => "webperl", 
    "Apache::ASP" => "apache::asp",

 
    ".NET" => ".net", 
    "ASP.NET" => "asp.net", 
    "ASP.NET Core" => "asp.net core", 
    "WCF" => "wcf", 
    "WebForms" => "webforms", 
    "MVC" => "mvc", 
    "Nancy" => "nancy", 
    "ServiceStack" => "servicestack",

    "Haxe" => "haxe", 
    "Tink" => "tink", 
    "KoHx" => "kohx", 
    "HaxeFlixel" => "haxeflixel", 
    "HaxePunk" => "haxepunk", 
    "HaxeUI" => "haxeui", 
    "HXCPP" => "hxcpp", 
    "OpenFL" => "openfl",

    "Groovy" => "groovy", 
    "Grails" => "grails", 
    "Ratpack" => "ratpack", 
    "Spring Boot" => "spring boot", 
    "Spock" => "spock", 
    "Micronaut" => "micronaut", 
    "Geb" => "geb",

    "PowerShell" => "powershell", 
    "Azure Functions" => "azure functions", 
    "PowerShell Web Access" => "powershell web access", 
    "Pode" => "pode", 
    "PowerShell Universal Dashboard" => "powershell universal dashboard", 
    "Universal" => "universal", 
    "PowerShell Server" => "powershell server", 
    "REST APIs" => "rest apis"
];

return $backend;
